- name: install mitaka
  package: name={{ item }} state=latest
  with_items:
#    - centos-release-openstack-mitaka
    - python-openstackclient
    - openstack-selinux

- name: generate environment
  lineinfile: line="export {{ item.key }}={{ item.value }}" dest=/root/openstack-admin.rc state=present create=yes
  tags: config
  with_dict: "{{ openstack_env }}"

- name: generate services.xml
  tags:
    - config
    - clinit
  local_action: template src="services.xml.j2" dest={{ inventory_dir }}/workdir/services.xml
  run_once: true
